### ISSUE TITLE
rename matchSource property & support multiple patterns

### ISSUE THREAD

**Issue by megastef** [fbalicchia/logagent-input-filter-grok#1]
Hi, 

other Logagent plugins `matchSource` is used to match the source name of a log (e.g. filename or container/image name). See e.g. https://sematext.com/docs/logagent/input-filter-grep/

I would suggest adding a matchSource function, filtering on the log source name and use `patterns` as name for the GROK patterns.  In addition, it would be handy to support more than 1 GROK pattern. The configuration would look like this: 

 ```
input: 
    files: 
      - /var/log/access.log

inputFilter:
  - module: grok
    config:
      matchSource: access\.log|nginx\.log
      patterns: 
        - '%{IP:client} \[%{TIMESTAMP_ISO8601:timestamp}\] "%{WORD:method} %{URIHOST:site}%{URIPATHPARAM:url}" %{INT:code} %{INT:request} %{INT:response} - %{NUMBER:took} \[%{DATA:cache}\] "%{DATA:mtag}" "%{DATA:agent}"'
      filePath: /tmp/grok-patterns
      idpattern: USER
```

Stefan
